version: '2.1'

services:
  jsreport:
    image: jsreport/jsreport
    container_name: jsreport
    hostname: jsreport
    ports:
      - 5488:5488

  consul:
    image: consul
    container_name: consul
    hostname: localhost
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: localhost
    ports:
      - 9411:9411
    
  mongo:
    image: mongo
    container_name: mongo
    hostname: localhost
    ports:
      - 27017:27017

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    hostname: localhost
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka_manager:
    image: mzagar/kafka-manager-docker:1.3.3.4
    container_name: kafkamanager
    hostname: localhost

    ports:
      - 9001:9000
    environment:
      ZK_HOSTS: 'zookeeper:2181'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
        - 9200:9200

  mn-documents-service:
    build: ./documents-service
    image: mn-documents-service
    container_name: mn-documents-service
    
  mn-policy-service:
    build: ./policy-service
    image: mn-policy-service
    container_name: mn-policy-service
    
  mn-policy-search-service:
    build: ./policy-search-service
    image: mn-policy-search-service
    container_name: mn-policy-search-service
    
  mn-pricing-service:
    build: ./pricing-service
    image: mn-pricing-service
    container_name: mn-pricing-service
    
  mn-payment-service:
    build: ./payment-service
    image: mn-payment-service
    container_name: mn-payment-service
    
  mn-product-service:
    build: ./product-service
    image: mn-product-service
    container_name: mn-product-service
    
  mn-auth-service:
    build: ./auth-service
    image: mn-auth-service
    container_name: mn-auth-service
    
  mn-chat-service:
    build: ./chat-service
    image: mn-chat-service
    container_name: mn-chat-service
    
  mn-dashboard-service:
    build: ./dashboard-service
    image: mn-dashboard-service
    container_name: mn-dashboard-service
    
  mn-agent-portal-gateway:
    build: ./agent-portal-gateway
    image: mn-agent-portal-gateway
    container_name: mn-agent-portal-gateway
    
  mn-web-vue:
    build: ./web-vue
    image: mn-web-vue
    container_name: mn-web-vue
    