micronaut:
  application:
    name: policy-service
  server:
    host: host.docker.internal
    port: ${SERVICE_PORT:-1}
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
---
jpa:
 default:
    packages-to-scan:
        - 'by.atsitou.policy.domain'
    properties:
        hibernate:
            hbm2ddl:
                auto: create-drop
            show_sql: true
---
jackson:
  serialization:
    failOnEmptyBeans: false
    writeDatesAsTimestamps: true
---
kafka:
#  embedded:
#    enabled: true
  bootstrap:
    servers: "${KAFKA_HOST:host.docker.internal}:${KAFKA_PORT:9092}"
---
consul:
  client:
    registration:
      enabled: true
      check:
        http: true
    defaultZone: "${CONSUL_HOST:host.docker.internal}:${CONSUL_PORT:8500}"
---
endpoints:
  health:
    enabled: true
    sensitive: false
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:host.docker.internal}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.
