micronaut:
  application:
    name: policy-search-service
  server:
    host: host.docker.internal
    port: ${SERVICE_PORT:-1}
---
jpa:
 default:
    packages-to-scan:
        - 'by.atsitou.policy.search.readmodel'
    properties:
        hibernate:
            hbm2ddl:
                auto: update
            show_sql: true
---
jackson:
  serialization:
    failOnEmptyBeans: false
    writeDatesAsTimestamps: true
---
kafka:
  bootstrap:
    servers: "${KAFKA_HOST:host.docker.internal}:${KAFKA_PORT:9092}"
---
consul:
  client:
    registration:
      enabled: true
      check:
        http: true
    defaultZone: "${CONSUL_HOST:host.docker.internal}:${CONSUL_PORT:8500}"
---
endpoints:
  health:
    enabled: true
    sensitive: false
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:host.docker.internal}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.
---
elastic:
    host: ${ELASTIC_HOST:localhost}
    port: ${ELASTIC_PORT:9200}
    connectionTimeout: 5000
    connectionRequestTimeout: 5000
    socketTimeout: 5000
    maxRetryTimeout: 5000
